### ISSUE TITLE
Can't get it running with Django-Vite

### ISSUE THREAD

**Issue by MichaelNZ85** [inertiajs/inertia-django#1]
I tried to set up Django with Inertia and Vue 3 by forking and cloning the Django Vite example repo and then adding the Inertia config. However, I have run into a problem - Vite fails with the following error:

```
failed to load config from D:\Projects\Python\django-vite-example\vite.config.js
error when starting dev server:
TypeError: vite.createFilter is not a function
    at vuePlugin (D:\Projects\Python\django-vite-example\node_modules\@vitejs\plugin-vue\dist\index.cjs:2549:23)
    at Object.<anonymous> (D:\Projects\Python\django-vite-example\vite.config.js:24:43)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.require.extensions.<computed> [as .js] (D:\Projects\Python\django-vite-example\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:70789:20)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadConfigFromBundledFile (D:\Projects\Python\django-vite-example\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:70797:17)
    at loadConfigFromFile (D:\Projects\Python\django-vite-example\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:70718:32)
error Command failed with exit code 1.
```

I'm not sure what's going on here as googling the error message didn't lead to any relevant information.

You can check my setup [here](https://github.com/MichaelNZ85/django-vite-example/tree/add-inertia).

**Comment by MichaelNZ85** [comment]
Thanks @mercuryseries ! I followed your tutorial and managed to set up React. 

I'm now trying to setup Vue, but I've run into [a major error](https://github.com/MichaelNZ85/DjangoViteInertia/blob/add-vue/error.log). Not sure what's going on here but Vite's dependency pre-bundling is failing. The top-level error message reads as follows:

```
X [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "function-bind". The package may have incorrect main/module/exports specified in its package.json.
```

You can check out the code [here](https://github.com/MichaelNZ85/DjangoViteInertia/tree/add-vue).

**Comment by MichaelNZ85** [comment]
Thank you so much for your help! I've got it working!
