### ISSUE TITLE
Setup method not working while testing

### ISSUE THREAD

**Issue by pvpmartins** [inertiajs/inertia-django#41]
So, I would like to use the very handy setup method in order to make some test cases without repeating myself.

```
class RegisterViewTest(InertiaTestCase):
    def setUp(self):
        # Setup run before every test method.
        self.test_user = User.objects.create_user(username='testuser', password='testpassword')
```

But unfortunately i get this error:

```
Traceback (most recent call last):
  File "/home/pvpmartins/nutrify/myenv/lib/python3.11/site-packages/inertia/test.py", line 25, in tearDown
    self.mock_inertia.stop()
    ^^^^^^^^^^^^^^^^^
AttributeError: 'RegisterViewTest' object has no attribute 'mock_inertia'

======================================================================
ERROR: test_register_and_login_pro_user (nutrifyapp.tests.RegisterViewTest.test_register_and_login_pro_user)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pvpmartins/nutrify/myenv/lib/python3.11/site-packages/inertia/test.py", line 25, in tearDown
    self.mock_inertia.stop()
    ^^^^^^^^^^^^^^^^^
AttributeError: 'RegisterViewTest' object has no attribute 'mock_inertia'

```

**Comment by CalElAn** [comment]
Hi I'm also facing this error. Were you able to solve it?

**Comment by BrandonShar** [comment]
Hi @pvpmartins , since you're subclassing `InertiaTestCase`, you'll need to make sure to call `super().setUp()` in your setup function (and do the same in tearDown if you override that method!).
